name: Generate story

on:
  # schedule:
  #   - cron: "0 0 * * 1,3,5"
  workflow_dispatch:

env:
  OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}

jobs:
  generate-story:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/themkat/aitales_story_generator:662e02fdb9b5c40347a7a9fbdd05294742a5b004
      credentials:
        username: themkat
        password: ${{  secrets.GITHUB_TOKEN }}
    steps:
      - name: generate story
        working-directory: /
        run: |
          /story_generator
