name: Generate story

on:
  # schedule:
  #   - cron: "0 0 * * 1,3,5"
  workflow_dispatch:

env:
  OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}

jobs:
  generate-story:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/themkat/aitales_story_generator:1e04d0de6bc65713437af4b32007951e00754a38
      credentials:
        username: themkat
        password: ${{  secrets.GITHUB_TOKEN }}
    steps:
      - name: generate story
        working-directory: /
        env:
          RUST_BACKTRACE: 1
        run: |
          /story_generator
      - uses: actions/checkout@v3
      - name: Transform stories to jekylls markdown format
        id: transform
        env:
          TITLE_FILE: /story_title.txt
          IMAGE_URL_FILE: /story_image_url.txt
          TEXT_FILE: /story_text.txt
          CATEGORY_FILE: /story_genre.txt
        run: |
          GEN_FILENAME=$(./.github/scripts/transform_to_story.sh)
          echo "postfile=_posts/$GEN_FILENAME.md" >> $GITHUB_OUTPUT
          echo "imagefile=assets/images/$GEN_FILENAME.md" >> $GITHUB_OUTPUT
          echo "title=$(cat $TITLE_FILE | tr -d '\n' | tr -d '\"')"
          echo "branchname=story-$(date '+%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5-beta
        with:
          add-paths: ${{ steps.transform.outputs.postfile }},${{ steps.transform.outputs.postfile }}
          commit-message: "New story: ${{ steps.transform.outputs.title }}"
          title: "New story: ${{ steps.transform.outputs.title }}"
          body: "New story! pls review me"
          branch: ${{ steps.transform.outputs.branchname }}
          reviewers: themkat
