name: Generate story

on:
  # schedule:
  #   - cron: "0 0 * * 1,3,5"
  workflow_dispatch:

env:
  OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}

jobs:
  generate-story:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/themkat/aitales_story_generator:f343690fa2feaf50f89cc70d0672aff31d03a11d
      credentials:
        username: themkat
        password: ${{  secrets.GITHUB_TOKEN }}
    steps:
      - name: generate story
        working-directory: /
        env:
          RUST_BACKTRACE: 1
        run: |
          /story_generator
      - uses: actions/checkout@v3
      - name: Configure git
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global user.name 'actions (automatic)'
          git config --global user.email 'action@github.com'
      - name: Transform stories to jekylls markdown format
        id: transform
        env:
          TITLE_FILE: /story_title.txt
          IMAGE_URL_FILE: /story_image_url.txt
          TEXT_FILE: /story_text.txt
          CATEGORY_FILE: /story_genre.txt
        run: |
          GEN_FILENAME=$(./.github/scripts/transform_to_story.sh)
          echo "title=$(cat $TITLE_FILE | tr -d '\n' | tr -d '\"')"
          BRANCH_NAME=story-$(date '+%Y-%m-%d_%H-%M')
          echo "branchname=$BRANCH_NAME" >> $GITHUB_OUTPUT
          git checkout -b $BRANCH_NAME
          git add _posts/$GEN_FILENAME.md
          git add assets/images/$GEN_FILENAME.png
          git push --set-upstream origin $BRANCH_NAME
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          gh pr create --title "New story: ${{ steps.transform.outputs.title }}" --body "New story! pls review me"
